// packages/svelte-app/src/components/Hero.svelte
<script>
	import logo from '../assets/logo.png';
	import SearchInput from './SearchInput.svelte';
</script>

<section class="hero">
	<div class="inner-hero">
		<div class="logo-wrapper">
			<img class="logo" src={logo} alt="Mewi Logo" />
		</div>
		<div class="search-box">
			<h3>Hitta begagnade produkter på ett enda ställe</h3>
			<SearchInput />
		</div>
	</div>
</section>

<style lang="scss">
	.hero {
		height: 50vh;
		width: 100%;
		background-color: $primary;
		display: flex;
		align-items: center;
		justify-content: center;
	}

	.inner-hero {
		display: flex;
		width: 100%;
		max-width: map-get($grid-breakpoints, lg);
		align-items: center;
		justify-content: space-between;

		& > * + * {
			margin-left: 2rem;
		}

		@media screen and (max-width: map-get($grid-breakpoints, lg)) {
			flex-direction: column;
			justify-content: center;
			align-items: center;

			& > * + * {
				margin-top: calc(1vw + 3rem);
				margin-left: 0;
			}

			.search-box {
				width: 100%;

				& > h3 {
					text-align: center;
				}
			}

			.logo {
				width: calc(18rem + 18vw);
			}
		}
	}

	.logo-wrapper {
		flex-grow: 1;
	}

	.logo {
		width: 100%;
		max-width: 32rem;
		height: auto;
	}

	.search-box {
		flex: none;
		max-width: 26rem;
		display: flex;
		flex-direction: column;
		align-items: center;
		color: white;

		& > h3 {
			margin-bottom: 1rem;
		}
	}
</style>

// packages/webapp/src/components/Hero/Hero.tsx
import style from './Hero.module.scss'
import { SearchInput } from 'components/SearchInput/SearchInput'

export const Hero = () => {
    return (
        <section className={style.hero}>
            <div className={style['inner-hero']}>
                <div className={style['logo-wrapper']}>
                    <img className={style.logo} src='/img/logo.png' alt='Mewi Logo' />
                </div>
                <div className={style['search-box']}>
                    <h3>Hitta begagnade produkter på ett enda ställe</h3>
                    <SearchInput />
                </div>
            </div>
        </section>
    )
}
