// packages/webapp/src/components/ArticleItem/OriginLabel.tsx
import { IListing } from '@wille430/common'

interface Props {
    origin: IListing['origin']
}

const OriginLabel = ({ origin }: Props) => {
    let className = 'h-full my-auto '

    switch (origin) {
        case 'Blocket':
            className += 'text-red-400'
            break
        case 'Tradera':
            className += 'text-green-500'
            break
        case 'Sellpy':
            className += 'text-gray-700'
            break
        default:
            break
    }

    return <span className={className}>{origin}</span>
}

export default OriginLabel

// packages/svelte-app/src/components/OriginLabel.svelte
<script lang="ts">
	import type { ListingOrigins } from '@wille430/common';
	export let origin: ListingOrigins;

	const originColors: Record<ListingOrigins, string> = {
		Blocket: 'red',
		Blipp: 'green',
		Tradera: 'green',
		Sellpy: 'black'
	};
</script>

<span style="color: {originColors[origin]};">
	{origin}
</span>
