// packages/webapp/src/components/SearchInput/SearchInput.tsx
import { Button } from '@mewi/ui'

export const SearchInput = () => {
    return (
        <div className='flex flex-col w-full items-end'>
            <form className='flex mx-auto w-full' action='/sok'>
                <input
                    className='p-2 rounded-l-md px-4 w-full max-w-sm text-black'
                    type='text'
                    name='query'
                    placeholder='Vad letar du efter?'
                />
                <Button className='rounded-l-none' color='secondary' type='submit' label='Sök' />
            </form>

            <a className='text-secondary mt-2' href='/filter'>
                {'Advancerade filter >>'}
            </a>
        </div>
    )
}

// packages/svelte-app/src/components/SearchInput.svelte
<script lang="ts">
	let query = '';
</script>

<div class="form-group d-flex flex-column">
	<form action="/sok" class="input-group">
		<input
			class="form-control"
			type="text"
			name="query"
			bind:value={query}
			placeholder="Vad letar du efter?"
		/>
		<input class="btn btn-secondary" type="submit" value="Sök" />
	</form>

	<a class="text-secondary small text-end mt-2" href="/filter">Advancerade filter >></a>
</div>

<style lang="scss">
	.input-group {
		width: 24rem;
		max-width: 100%;
	}
</style>
