// packages/svelte-app/src/components/SearchInput.svelte
<script lang="ts">
	let query = '';
</script>

<div class="form-group d-flex flex-column">
	<form action="/sok" class="input-group">
		<input
			class="form-control"
			type="text"
			name="query"
			bind:value={query}
			placeholder="Vad letar du efter?"
		/>
		<input class="btn btn-secondary" type="submit" value="Sök" />
	</form>

	<a class="text-secondary small text-end mt-2" href="/filter">Advancerade filter >></a>
</div>

<style lang="scss">
	.input-group {
		width: 24rem;
		max-width: 100%;
	}
</style>

// apps/next-client/src/components/SearchInput/SearchInput.tsx
import clsx from 'clsx'
import type {HTMLAttributes} from 'react'
import {Button} from '../Button/Button'

export const SearchInput = (props: HTMLAttributes<HTMLInputElement>) => {
    const {className, ...rest} = props
    return (
        <form className="mx-auto flex w-full" action="/sok">
            <input
                className={clsx('w-full max-w-sm rounded-l-md p-2 px-4 text-black', className)}
                type="text"
                name="keyword"
                placeholder="Vad letar du efter?"
                {...rest}
            />
            <Button className="rounded-l-none bg-secondary" color="secondary" type="submit">Sök</Button>
        </form>
    )
}
