// packages/svelte-app/src/components/OriginLabel.svelte
<script lang="ts">
	import type { ListingOrigins } from '@wille430/common';
	export let origin: ListingOrigins;

	const originColors: Record<ListingOrigins, string> = {
		Blocket: 'red',
		Blipp: 'green',
		Tradera: 'green',
		Sellpy: 'black'
	};
</script>

<span style="color: {originColors[origin]};">
	{origin}
</span>

// packages/webapp/src/components/OriginLabel/OriginLabel.tsx
import type { ListingOrigins } from '@wille430/common'

export const OriginLabel = ({ origin }: { origin: ListingOrigins }) => {
    const originColors: Record<ListingOrigins, string> = {
        Blocket: 'red',
        Blipp: 'green',
        Tradera: 'green',
        Sellpy: 'black',
    }

    return <span style={{ color: originColors[origin] }}>{origin}</span>
}
